version : '3'
services:
    python:
        #image: python:3.6.9
        build:
            context: .
            dockerfile: docker/python/Dockerfile

        volumes:
            - ./core:/core
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: postgres

      
        